DROP DATABASE IF EXISTS SPAZIO_DB;

CREATE DATABASE SPAZIO_DB;

USE SPAZIO_DB;

DROP TABLE IF EXISTS FOTOS;
DROP TABLE IF EXISTS LUGARES;

CREATE TABLE IF NOT EXISTS LUGARES (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    descripcion TEXT
);

CREATE TABLE IF NOT EXISTS FOTOS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    id_lugar INT NOT NULL,
    foto VARCHAR(255) NOT NULL,
    FOREIGN KEY (id_lugar) REFERENCES LUGARES(id) ON DELETE CASCADE
);